#!/bin/bash

echo "🚀 GitHub Pages Domain Takeover Başlıyor..."
echo ""
echo "📋 YAPILACAKLAR:"
echo "1. GitHub.com'da yeni hesap aç (varsa giriş yap)"
echo "2. Kullanıcı adı: kayserisuyalitimi (veya benzeri)"
echo "3. Yeni repository oluştur: kayserisuyalitimi.github.io"
echo "4. Repository'yi public yap"
echo ""
echo "📌 GIT REMOTE EKLE:"
echo "git remote add origin https://github.com/kayserisuyalitimi/kayserisuyalitimi.github.io.git"
echo ""
echo "📤 PUSH ET:"
echo "git push -u origin master"
echo ""
echo "⚙️ GITHUB PAGES AYARLARI:"
echo "1. Settings > Pages"
echo "2. Source: Deploy from branch"
echo "3. Branch: master / root"
echo "4. Custom domain: kayserisuyalitimi.com"
echo ""
echo "✅ DOMAIN OTOMATİK ÇALIŞIR!"
echo "CNAME dosyası zaten hazır, GitHub otomatik tanıyacak"
echo ""
echo "🔗 Alternatif domainler de kullanılabilir:"
echo "- kayserisuyalitimi.net"
echo "- kayserisuyalitimi.com.tr"
echo "- kayserisuyalitimi.online"
